// <auto-generated />
using System;
using AshamedApp.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AshamedApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250112194953_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AshamedApp.Application.DTOs.MqttMessageDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SnapshotDtoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDtoId");

                    b.ToTable("MqttMessages");
                });

            modelBuilder.Entity("AshamedApp.Application.DTOs.SnapshotDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MqttMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("SnapshotMqttMessage", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MqttMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SnapshotId", "MqttMessageId");

                    b.HasIndex("MqttMessageId");

                    b.ToTable("SnapshotMqttMessages", (string)null);
                });

            modelBuilder.Entity("AshamedApp.Application.DTOs.MqttMessageDto", b =>
                {
                    b.HasOne("AshamedApp.Application.DTOs.SnapshotDto", null)
                        .WithMany("Messages")
                        .HasForeignKey("SnapshotDtoId");
                });

            modelBuilder.Entity("SnapshotMqttMessage", b =>
                {
                    b.HasOne("AshamedApp.Application.DTOs.MqttMessageDto", null)
                        .WithMany()
                        .HasForeignKey("MqttMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AshamedApp.Application.DTOs.SnapshotDto", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AshamedApp.Application.DTOs.SnapshotDto", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
